RSE-812: Fix: not importing logs from azure
rundeck-plugins/rundeck-azure-plugin pull request #37
Opened 2023-10-02 20:31 UTC by L2JE

Ticket: https://pagerduty.atlassian.net/browse/RSE-740
Depends on: https://github.com/rundeck/rundeck/pull/8583

Support the use of outputfilepath execution context variable to access log files in case the isRemoteFilePath variable is true, meaning is an imported execution.

2023-10-19 17:39 UTC, ronaveva requested changes
add javadoc to new method

2023-10-19 17:39 UTC, ronaveva commented on src/main/groovy/com/rundeck/plugins/azure/plugin/AzureFileStoragePlugin.groovy
> +    protected static boolean isImportedExecution(Map<String, ?> context){
please add javadoc

2023-10-19 19:30 UTC, ronaveva approved these changes
LGTM

2023-10-23 12:37 UTC, L2JE commented
Waiting for core 4.17.2-rc1 to be released to set the correct dependency

2023-10-26 12:21 UTC, merged